spring.datasource.driver-class-name=xxx
spring.datasource.url=jdbc:postgresql://localhost:5432/xxx
spring.datasource.username=xxx
spring.datasource.password=xxx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true